package FRM;
import BUS.*;
import DAO.*;
import DTO.*;

import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Tommy
 */
public class KhachHangFRM extends javax.swing.JFrame {

    /**
     * Creates new form KhachHangFRM
     */
    DefaultTableModel model = new DefaultTableModel();
    //JTable tblDSKhachHang = new JTable();
    public KhachHangFRM() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDSKhachHang = new javax.swing.JTable();
        btnDoc = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        btnDatLai = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtMaKH1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtTenKH = new javax.swing.JTextField();
        txtNgaySinh = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtSDT = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCMND = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtGioiTinh = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtVisa = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtHang3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jrbtnKHD = new javax.swing.JRadioButton();
        jrbtnKHM = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        jrbtnMaKH1 = new javax.swing.JRadioButton();
        jrbtnVisa = new javax.swing.JRadioButton();
        txtTimVisa = new javax.swing.JTextField();
        txtTimMaKH1 = new javax.swing.JTextField();
        btnTim = new javax.swing.JButton();
        jrbtnTenKH = new javax.swing.JRadioButton();
        txtTimTenKH = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jrbtnSLKHM = new javax.swing.JRadioButton();
        jrbtnSLKHD = new javax.swing.JRadioButton();
        txtSL = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(100, 100));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblDSKhachHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Khách", "Tên Khách Hàng", "Ngày Sinh", "SDT", "CMND", "Giới Tính", "Visa"
            }
        ));
        tblDSKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDSKhachHangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDSKhachHang);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1360, 180));

        btnDoc.setText("Đọc");
        btnDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDocActionPerformed(evt);
            }
        });
        getContentPane().add(btnDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });
        getContentPane().add(btnThoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 360, -1, -1));

        btnDatLai.setText("Đặt Lại");
        btnDatLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatLaiActionPerformed(evt);
            }
        });
        getContentPane().add(btnDatLai, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 360, -1, -1));

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        getContentPane().add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, -1, -1));

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        getContentPane().add(btnSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, -1, -1));

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        getContentPane().add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, -1, -1));

        btnCapNhat.setText("Cập Nhật");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });
        getContentPane().add(btnCapNhat, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 360, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Quản Lý Khách Hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14), new java.awt.Color(102, 0, 0))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Mã KH");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 20, 52, 27));
        jPanel1.add(txtMaKH1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 173, 27));

        jLabel2.setText("Tên KH");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 58, 52, 27));
        jPanel1.add(txtTenKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 173, 27));
        jPanel1.add(txtNgaySinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 173, 27));

        jLabel4.setText("SDT");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 140, 27));
        jPanel1.add(txtSDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, 173, 27));

        jLabel5.setText("CMND");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 130, 27));
        jPanel1.add(txtCMND, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 60, 173, 27));

        jLabel6.setText("Giới Tính");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 140, 27));

        txtGioiTinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGioiTinhActionPerformed(evt);
            }
        });
        jPanel1.add(txtGioiTinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 100, 173, 27));

        jLabel7.setText("VISA");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 20, 40, 27));
        jPanel1.add(txtVisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 20, 173, 27));

        jLabel8.setText("Ngày Sinh");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 103, 70, 27));
        jPanel1.add(txtHang3, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 20, 173, 27));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 1050, 147));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 0, 0));
        jLabel3.setText("Hiển Thị");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 360, 71, 27));

        buttonGroup1.add(jrbtnKHD);
        jrbtnKHD.setText("Khách Hàng Đi");
        jrbtnKHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbtnKHDActionPerformed(evt);
            }
        });
        getContentPane().add(jrbtnKHD, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 360, -1, -1));

        buttonGroup1.add(jrbtnKHM);
        jrbtnKHM.setText("Khách Hàng Mua");
        jrbtnKHM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbtnKHMActionPerformed(evt);
            }
        });
        getContentPane().add(jrbtnKHM, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 390, -1, -1));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 0, 0));
        jLabel11.setText("Thống Kê");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 200, 71, 27));

        buttonGroup2.add(jrbtnMaKH1);
        jrbtnMaKH1.setText("Theo Mã KH");
        jrbtnMaKH1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jrbtnMaKH1ItemStateChanged(evt);
            }
        });
        jrbtnMaKH1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbtnMaKH1ActionPerformed(evt);
            }
        });
        getContentPane().add(jrbtnMaKH1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 360, -1, -1));

        buttonGroup2.add(jrbtnVisa);
        jrbtnVisa.setText("Theo VISA");
        jrbtnVisa.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jrbtnVisajrbtnMaVeItemStateChanged(evt);
            }
        });
        jrbtnVisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbtnVisaActionPerformed(evt);
            }
        });
        getContentPane().add(jrbtnVisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 420, 107, -1));

        txtTimVisa.setEnabled(false);
        getContentPane().add(txtTimVisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 420, 157, -1));

        txtTimMaKH1.setEnabled(false);
        txtTimMaKH1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimMaKH1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtTimMaKH1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 360, 157, -1));

        btnTim.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        btnTim.setForeground(new java.awt.Color(153, 0, 51));
        btnTim.setText("Tìm");
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });
        getContentPane().add(btnTim, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 360, 70, 80));

        buttonGroup2.add(jrbtnTenKH);
        jrbtnTenKH.setText("Theo Tên KH");
        jrbtnTenKH.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jrbtnTenKHjrbtnMaVeItemStateChanged(evt);
            }
        });
        jrbtnTenKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbtnTenKHActionPerformed(evt);
            }
        });
        getContentPane().add(jrbtnTenKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 390, 107, -1));

        txtTimTenKH.setEnabled(false);
        getContentPane().add(txtTimTenKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 390, 157, -1));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 0, 0));
        jLabel12.setText("Tìm Kiếm");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 360, 71, 27));

        buttonGroup3.add(jrbtnSLKHM);
        jrbtnSLKHM.setText("Sl Khách Hàng Mua");
        jrbtnSLKHM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbtnSLKHMActionPerformed(evt);
            }
        });
        getContentPane().add(jrbtnSLKHM, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 260, -1, -1));

        buttonGroup3.add(jrbtnSLKHD);
        jrbtnSLKHD.setText("SL Khách Hàng Đi");
        jrbtnSLKHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbtnSLKHDActionPerformed(evt);
            }
        });
        getContentPane().add(jrbtnSLKHD, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 230, -1, -1));
        getContentPane().add(txtSL, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 240, 60, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel9.setText("người");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 240, 40, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDocActionPerformed
       KhachHangBUS bus = new KhachHangBUS();
       if(KhachHangBUS.dskh==null) bus.docDSKH();
       Vector header = new Vector();
       header.add("Mã Khách");
       header.add("Tên Khách Hàng");
       header.add("Ngày Sinh");
       header.add("CMND");
       header.add("SDT");
       header.add("Giới Tính");
       header.add("Visa");
       model = new DefaultTableModel(header,0);
       for(KhachHangDTO kh : KhachHangBUS.dskh)
       {
           Vector row = new Vector();
           row.add(kh.MaKH);
           row.add(kh.TenKH);
           row.add(kh.NgaySinh);
           row.add(kh.CMND);
           row.add(kh.SDT);
           row.add(kh.GioiTinh);
           row.add(kh.Visa);
           model.addRow(row);
       }
       tblDSKhachHang.setModel(model);
    }//GEN-LAST:event_btnDocActionPerformed

    private void txtGioiTinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGioiTinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGioiTinhActionPerformed

    private void tblDSKhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDSKhachHangMouseClicked
        int k=tblDSKhachHang.getSelectedRow();
				if(k>=0)
				{
					txtMaKH1.setText(tblDSKhachHang.getModel().getValueAt(k,0).toString());
					txtTenKH.setText(tblDSKhachHang.getModel().getValueAt(k,1).toString());
					txtNgaySinh.setText(tblDSKhachHang.getModel().getValueAt(k,2).toString());
					txtCMND.setText(tblDSKhachHang.getModel().getValueAt(k,3).toString());
					txtSDT.setText(tblDSKhachHang.getModel().getValueAt(k,4).toString());
					txtGioiTinh.setText(tblDSKhachHang.getModel().getValueAt(k,5).toString());
					txtVisa.setText(tblDSKhachHang.getModel().getValueAt(k,6).toString());
                                        
				}
        /*boolean a=tblDSVeMayBay.isEditing();
        if(a==false)
        {
            JOptionPane.showMessageDialog(null,"Không được phép điều chỉnh !!!");
        }*/
        tblDSKhachHang.setDefaultEditor(Object.class, null);
    }//GEN-LAST:event_tblDSKhachHangMouseClicked
    public static boolean checkNumber(String s)
    {
        for(int i =0 ; i< s.length(); i++){
            if(Character.isDigit(s.charAt(i))){
               
            }else return false;
        }
        return true;
    }
    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
                                String mk = txtMaKH1.getText();
                                String cmnd = txtCMND.getText();
                                String sdt = txtSDT.getText();
                                int flag=0;
                                if("".equals(mk))
                                {
                                    JOptionPane.showMessageDialog(null, "Mã khách hàng trống !");
                                    txtMaKH1.requestFocus();
                                    flag=1;
                                }else
                                if(checkNumber(txtCMND.getText())==false)
                                {
                                    JOptionPane.showMessageDialog(null, "CMND không hợp lệ !");
                                    txtCMND.setText("");
                                    txtCMND.requestFocus();
                                    flag=1;
                                }else
                                if(txtSDT.getText().length() > 11 || checkNumber(txtSDT.getText())==false)
                                {
                                    JOptionPane.showMessageDialog(null, "SDT không hợp lệ !");
                                    txtSDT.setText("");
                                    txtSDT.requestFocus();
                                    flag=1;
                                }
                                for(KhachHangDTO kh : KhachHangBUS.dskh)
                                {
                                    if(mk.equals(kh.getMaKH()))
                                    {
                                        JOptionPane.showMessageDialog(null, "Mã khách hàng bị trùng !");
                                        flag=1;
                                    }
                                }
                                if(flag==0)
                                {            
                                JOptionPane.showMessageDialog(null, "Đã thêm dữ liệu !");
                                KhachHangDTO kh=new KhachHangDTO();
				kh.setMaKH(txtMaKH1.getText().toUpperCase());
				kh.setTenKH(txtTenKH.getText());
				kh.setNgaySinh(txtNgaySinh.getText());
				kh.setCMND(txtCMND.getText());
                                kh.setSDT(txtSDT.getText());
				kh.setGioiTinh(txtGioiTinh.getText());
				kh.setVisa(txtVisa.getText().toUpperCase());
				
                                Vector row=new Vector();
				row.add(kh.getMaKH());
				row.add(kh.getTenKH());
				row.add(kh.getNgaySinh());
				row.add(kh.getCMND());
                                row.add(kh.getSDT());
				row.add(kh.getGioiTinh());
                                row.add(kh.getVisa());
				
                                model.addRow(row);
				tblDSKhachHang.setModel(model);
                                KhachHangBUS bus = new KhachHangBUS();
				bus.them(kh);
                                }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        int k=JOptionPane.showConfirmDialog(null,"Bạn chắc chắn muốn sửa ?");
				if(k==0)
				{
					int i=tblDSKhachHang.getSelectedRow();
					if(i>=0)
					{
						JOptionPane.showMessageDialog(null,"Sửa thành công !");
						KhachHangDTO kh=new KhachHangDTO();
                                                kh.setMaKH(txtMaKH1.getText().toUpperCase());
                                                kh.setTenKH(txtTenKH.getText());
                                                kh.setNgaySinh(txtNgaySinh.getText());
                                                kh.setCMND(txtCMND.getText());
                                                kh.setSDT(txtSDT.getText());
                                                kh.setGioiTinh(txtGioiTinh.getText());
                                                kh.setVisa(txtVisa.getText().toUpperCase());
						
						tblDSKhachHang.getModel().setValueAt(kh.getMaKH(),i,0);
						tblDSKhachHang.getModel().setValueAt(kh.getTenKH(),i,1);
						tblDSKhachHang.getModel().setValueAt(kh.getNgaySinh(),i,2);
						tblDSKhachHang.getModel().setValueAt(kh.getCMND(),i,3);
						tblDSKhachHang.getModel().setValueAt(kh.getSDT(),i,4);
						tblDSKhachHang.getModel().setValueAt(kh.getGioiTinh(),i,5);
                                                tblDSKhachHang.getModel().setValueAt(kh.getVisa(),i,6);
						
						KhachHangBUS bus=new KhachHangBUS();
						bus.sua(i,kh);
                                            
					}
					else JOptionPane.showMessageDialog(null,"Chọn dòng cần sửa !");	
				}
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
       int i=tblDSKhachHang.getSelectedRow();
				int k=JOptionPane.showConfirmDialog(null,"Bạn chắc chắn muốn xóa ?");
				if(k==0)
				{
					if(i>=0)
					{
						JOptionPane.showMessageDialog(null,"Đã xóa dữ liệu !");
						KhachHangBUS bus=new KhachHangBUS();
						bus.xoa(i, tblDSKhachHang.getModel().getValueAt(i,0).toString());
						model.removeRow(i);
						tblDSKhachHang.setModel(model);
						
					}
					else JOptionPane.showMessageDialog(null,"Vui lòng chọn dòng cần xóa !");
				}
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnDatLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatLaiActionPerformed
                                txtMaKH1.setText("");
                                txtTenKH.setText("");
				txtNgaySinh.setText("");
				txtCMND.setText("");
				txtSDT.setText("");
				txtGioiTinh.setText("");
                                txtVisa.setText("");
    }//GEN-LAST:event_btnDatLaiActionPerformed
    public void newTableKH()
	{
		model=new DefaultTableModel();
		Vector header=new Vector();
		header.add("Mã Khách");
		header.add("Tên Khách Hàng");
		header.add("Ngày Sinh");
		header.add("CMND");
		header.add("SDT");
		header.add("Giới Tính");
                header.add("Visa");
                		
		if(model.getRowCount()==0)
			model=new DefaultTableModel(header,0);
		tblDSKhachHang.setModel(model);
	}
	public void newDataModel()
	{
		for(KhachHangDTO kh : KhachHangBUS.dskh)
		{
			Vector row=new Vector();
			row.add(kh.getMaKH());
			row.add(kh.getTenKH());
			row.add(kh.getNgaySinh());
                        row.add(kh.getCMND());
			row.add(kh.getSDT());
			row.add(kh.getGioiTinh());
			row.add(kh.getVisa());
		
                        model.addRow(row);
		}
		tblDSKhachHang.setModel(model);
	}
        public void setTable() 
	{
		KhachHangBUS bus=new KhachHangBUS();
		if(KhachHangBUS.dskh==null) bus.docDSKH();
		
		newTableKH();
		newDataModel();
	}
    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
                                KhachHangBUS bus=new KhachHangBUS();
				bus.docDSKH();
				model =new DefaultTableModel();
				tblDSKhachHang.setModel(model);
				setTable();
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
       int i=JOptionPane.showConfirmDialog(null, "Bạn chắc chắn muốn thoát ?");
       if (i==0)
       {
           System.exit(0);
       }
    }//GEN-LAST:event_btnThoatActionPerformed

    private void jrbtnKHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbtnKHDActionPerformed
        newTableKH();
        KhachHangBUS bus = new KhachHangBUS();
        bus.hienThi("MaKH","KHD");
        newDataModel();
    }//GEN-LAST:event_jrbtnKHDActionPerformed

    private void jrbtnKHMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbtnKHMActionPerformed
        newTableKH();
        KhachHangBUS bus = new KhachHangBUS();
        bus.hienThi("MaKH","KHM");
        newDataModel();
    }//GEN-LAST:event_jrbtnKHMActionPerformed

    private void jrbtnMaKH1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jrbtnMaKH1ItemStateChanged

    }//GEN-LAST:event_jrbtnMaKH1ItemStateChanged

    private void jrbtnMaKH1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbtnMaKH1ActionPerformed
        txtTimMaKH1.setEnabled(true);
        txtTimTenKH.setText("");
        txtVisa.setText("");
        txtTimTenKH.setEnabled(false);
        txtTimVisa.setEnabled(false);
        txtTimMaKH1.requestFocus();
    }//GEN-LAST:event_jrbtnMaKH1ActionPerformed

    private void jrbtnVisajrbtnMaVeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jrbtnVisajrbtnMaVeItemStateChanged

    }//GEN-LAST:event_jrbtnVisajrbtnMaVeItemStateChanged

    private void jrbtnVisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbtnVisaActionPerformed
        txtTimVisa.setEnabled(true);
        txtTimMaKH1.setText("");
        txtTimTenKH.setText("");
        txtTimMaKH1.setEnabled(false);
        txtTimTenKH.setEnabled(false);
        txtTimVisa.requestFocus();
    }//GEN-LAST:event_jrbtnVisaActionPerformed

    private void txtTimMaKH1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimMaKH1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimMaKH1ActionPerformed

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        if(jrbtnMaKH1.isSelected())
        {
            newTableKH();
            KhachHangBUS bus = new KhachHangBUS();
            bus.timKiem("MaKH",txtTimMaKH1.getText());
            newDataModel();
        }
        else if (jrbtnTenKH.isSelected())
        {
            newTableKH();
            KhachHangBUS bus = new KhachHangBUS();
            bus.timKiem("TenKH",txtTimTenKH.getText());
            newDataModel();
        }
        else if (jrbtnVisa.isSelected())
        {
            newTableKH();
            KhachHangBUS bus = new KhachHangBUS();
            bus.timKiem("Visa",txtTimVisa.getText());
            newDataModel();
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Vui lòng chọn ô cần tìm !");
        }

        /* i=cbbTimKiem_HD.getSelectedIndex();
        if(i==0)
        {
            JOptionPane.showMessageDialog(null,"Vui lĂ²ng chá»?n loáº¡i muá»‘n tĂ¬m.");
        }
        else if(i==1)
        {
            newTableHD();
            HoaDonBUS bus=new HoaDonBUS();
            bus.timKiem("MaHD",txtTimKiemHD.getText());
            newDataModel();
        }
        else if(i==2)
        {
            newTableHD();
            HoaDonBUS bus=new HoaDonBUS();
            bus.timKiem("MaKH",txtTimKiemHD.getText());
            newDataModel();
        }
        else if(i==3)
        {
            newTableHD();
            HoaDonBUS bus=new HoaDonBUS();
            bus.timKiem("MaNV",txtTimKiemHD.getText());
            newDataModel();
        }*/
    }//GEN-LAST:event_btnTimActionPerformed

    private void jrbtnTenKHjrbtnMaVeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jrbtnTenKHjrbtnMaVeItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbtnTenKHjrbtnMaVeItemStateChanged

    private void jrbtnTenKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbtnTenKHActionPerformed
        txtTimTenKH.setEnabled(true);
        txtTimMaKH1.setText("");
        txtTimVisa.setText("");
        txtTimMaKH1.setEnabled(false);
        txtTimVisa.setEnabled(false);
        txtTimTenKH.requestFocus();
    }//GEN-LAST:event_jrbtnTenKHActionPerformed

    private void jrbtnSLKHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbtnSLKHDActionPerformed
        KhachHangDAO dao =new KhachHangDAO();
        txtSL.setText(Integer.toString(dao.thongKeDi_Mua("KHD")));
    }//GEN-LAST:event_jrbtnSLKHDActionPerformed

    private void jrbtnSLKHMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbtnSLKHMActionPerformed
        KhachHangDAO dao =new KhachHangDAO();
        txtSL.setText(Integer.toString(dao.thongKeDi_Mua("KHM")));
    }//GEN-LAST:event_jrbtnSLKHMActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KhachHangFRM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KhachHangFRM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KhachHangFRM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KhachHangFRM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KhachHangFRM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnDatLai;
    private javax.swing.JButton btnDoc;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnTim;
    private javax.swing.JButton btnXoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton jrbtnKHD;
    private javax.swing.JRadioButton jrbtnKHM;
    private javax.swing.JRadioButton jrbtnMaKH1;
    private javax.swing.JRadioButton jrbtnSLKHD;
    private javax.swing.JRadioButton jrbtnSLKHM;
    private javax.swing.JRadioButton jrbtnTenKH;
    private javax.swing.JRadioButton jrbtnVisa;
    private javax.swing.JTable tblDSKhachHang;
    private javax.swing.JTextField txtCMND;
    private javax.swing.JTextField txtGioiTinh;
    private javax.swing.JTextField txtHang3;
    private javax.swing.JTextField txtMaKH1;
    private javax.swing.JTextField txtNgaySinh;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtSL;
    private javax.swing.JTextField txtTenKH;
    private javax.swing.JTextField txtTimMaKH1;
    private javax.swing.JTextField txtTimTenKH;
    private javax.swing.JTextField txtTimVisa;
    private javax.swing.JTextField txtVisa;
    // End of variables declaration//GEN-END:variables
}
