package FRM;
import BUS.*;
import DAO.*;
import DTO.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import java.io.FileWriter;
import java.util.Vector;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Tommy
 */
public class VeMayBayFRM extends javax.swing.JFrame {

    /**
     * Creates new form VeMayBayFRM
     */
	JTable tblDSVeMayBay = new JTable();
    DefaultTableModel model = new DefaultTableModel ();
    private File file;
    public VeMayBayFRM() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    	
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        
        btnDoc = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtMaVe = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtMaGhe = new javax.swing.JTextField();
        txtMaKH = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtMaCB = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtTenHangVe = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtGiaVe = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtGiaTriGiam = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtVisa = new javax.swing.JTextField();
        txtHang = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        jrbtnMaVe = new javax.swing.JRadioButton();
        jrbtnMaKH = new javax.swing.JRadioButton();
        txtTimMaVe = new javax.swing.JTextField();
        txtTimMaKH = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnTim = new javax.swing.JButton();
        btnDatLai = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        btnXuat = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jrbtnTrongNuoc = new javax.swing.JRadioButton();
        jrbtnNgoaiNuoc = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản Lý Vé Máy Bay");
        setLocation(new java.awt.Point(100, 100));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblDSVeMayBay.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã Vé", "Mã Ghế", "Mã Khách ", "Mã Chuyến Bay", "Tên Hạng Vé", "Giá Vé (VND)", "Hãng", "Giá Trị Giảm (%)", "Visa"
            }
        ));
        tblDSVeMayBay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDSVeMayBayMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDSVeMayBay);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 1320, 189));

        btnDoc.setText("Đọc");
        btnDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDocActionPerformed(evt);
            }
        });
        getContentPane().add(btnDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 414, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Mã Vé");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 20, 52, 27));
        jPanel1.add(txtMaVe, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 173, 27));

        jLabel2.setText("Mã Ghế");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 58, 52, 27));
        jPanel1.add(txtMaGhe, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 170, 27));
        jPanel1.add(txtMaKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 173, 27));

        jLabel4.setText("Mã Chuyến Bay");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 140, 27));
        jPanel1.add(txtMaCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, 173, 27));

        jLabel5.setText("Tên Hạng Vé");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, 130, 27));
        jPanel1.add(txtTenHangVe, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 60, 173, 27));

        jLabel6.setText("Giá Vé");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, 140, 27));

        txtGiaVe.setText("0");
        txtGiaVe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGiaVeActionPerformed(evt);
            }
        });
        jPanel1.add(txtGiaVe, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 100, 173, 27));

        jLabel7.setText("Hãng");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 20, 40, 27));
        jPanel1.add(txtGiaTriGiam, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 60, 50, 27));

        jLabel8.setText("Mã Khách");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 103, 70, 27));

        jLabel10.setText("Giá Trị Giảm");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 60, 70, 27));

        jLabel12.setText("Visa");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 100, 40, 27));
        jPanel1.add(txtVisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 100, 173, 27));
        jPanel1.add(txtHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 20, 173, 27));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 235, 1320, 147));

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	ThemVe themve=new ThemVe();
            	themve.setVisible(true);
            	
            }
        });
        getContentPane().add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 414, -1, -1));

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        getContentPane().add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 414, -1, -1));

        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });
        getContentPane().add(btnThoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(589, 414, -1, -1));

        buttonGroup1.add(jrbtnMaVe);
        jrbtnMaVe.setText("Theo Mã Vé");
        jrbtnMaVe.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jrbtnMaVeItemStateChanged(evt);
            }
        });
        jrbtnMaVe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbtnMaVeActionPerformed(evt);
            }
        });
        getContentPane().add(jrbtnMaVe, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 400, -1, -1));

        buttonGroup1.add(jrbtnMaKH);
        jrbtnMaKH.setText("Theo Mã Khách");
        jrbtnMaKH.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jrbtnMaVeItemStateChanged(evt);
            }
        });
        jrbtnMaKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbtnMaKHActionPerformed(evt);
            }
        });
        getContentPane().add(jrbtnMaKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 430, 107, -1));

        txtTimMaVe.setEnabled(false);
        txtTimMaVe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimMaVeActionPerformed(evt);
            }
        });
        getContentPane().add(txtTimMaVe, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 400, 157, -1));

        txtTimMaKH.setEnabled(false);
        getContentPane().add(txtTimMaKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 430, 157, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 0, 0));
        jLabel3.setText("Hiển Thị");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 400, 71, 27));

        btnTim.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        btnTim.setForeground(new java.awt.Color(153, 0, 51));
        btnTim.setText("Tìm");
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });
        getContentPane().add(btnTim, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 400, 70, 51));

        btnDatLai.setText("Đặt lại");
        btnDatLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatLaiActionPerformed(evt);
            }
        });
        getContentPane().add(btnDatLai, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 414, -1, -1));

        btnCapNhat.setText("Cập Nhật");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });
        getContentPane().add(btnCapNhat, new org.netbeans.lib.awtextra.AbsoluteConstraints(424, 414, -1, -1));

        btnXuat.setText("Xuất");
        btnXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatActionPerformed(evt);
            }
        });
        getContentPane().add(btnXuat, new org.netbeans.lib.awtextra.AbsoluteConstraints(519, 414, -1, -1));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 0, 0));
        jLabel11.setText("Tìm Kiếm");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 400, 71, 27));

        buttonGroup2.add(jrbtnTrongNuoc);
        jrbtnTrongNuoc.setText("Vé Trong Nước");
        jrbtnTrongNuoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbtnTrongNuocActionPerformed(evt);
            }
        });
        getContentPane().add(jrbtnTrongNuoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 400, -1, -1));

        buttonGroup2.add(jrbtnNgoaiNuoc);
        jrbtnNgoaiNuoc.setText("Vé Ngoài Nước");
        jrbtnNgoaiNuoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbtnNgoaiNuocActionPerformed(evt);
            }
        });
        getContentPane().add(jrbtnNgoaiNuoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 430, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
   

//Button đọc
    private void btnDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDocActionPerformed
       VeMayBayBUS bus = new VeMayBayBUS();
       if(VeMayBayBUS.dsvmb==null) bus.docDSVMB();
       Vector header = new Vector();
       header.add("Mã Vé");
       header.add("Mã Ghế");
       header.add("Mã Khách");
       header.add("Mã Chuyến Bay");
       header.add("Tên Hạng vé");
       header.add("Giá Vé(VND)");
       header.add("Hãng");
       header.add("Giá trị giảm(%)");
       header.add("Visa");
       model = new DefaultTableModel(header,0);
       for(VeMayBayDTO vmb : VeMayBayBUS.dsvmb)
       {
           Vector row = new Vector();
           row.add(vmb.MaVe);
           row.add(vmb.MaGhe);
           row.add(vmb.MaKH);
           row.add(vmb.MaCB);
           row.add(vmb.TenHangVe);
           row.add(vmb.GiaVe);
           row.add(vmb.Hang);
           row.add(vmb.GiaTriGiam);
           row.add(vmb.Visa);
           model.addRow(row);
       }
       tblDSVeMayBay.setModel(model);
    }//GEN-LAST:event_btnDocActionPerformed
//Hiển thị Row ở Jtable lên từng TextField
    private void tblDSVeMayBayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDSVeMayBayMouseClicked
          int k=tblDSVeMayBay.getSelectedRow();
				if(k>=0)
				{
					txtMaVe.setText(tblDSVeMayBay.getModel().getValueAt(k,0).toString());
					txtMaGhe.setText(tblDSVeMayBay.getModel().getValueAt(k,1).toString());
					txtMaKH.setText(tblDSVeMayBay.getModel().getValueAt(k,2).toString());
					txtMaCB.setText(tblDSVeMayBay.getModel().getValueAt(k,3).toString());
					txtTenHangVe.setText(tblDSVeMayBay.getModel().getValueAt(k,4).toString());
					txtGiaVe.setText(tblDSVeMayBay.getModel().getValueAt(k,5).toString());
					txtGiaTriGiam.setText(tblDSVeMayBay.getModel().getValueAt(k,7).toString());
                   
                                        txtVisa.setText(tblDSVeMayBay.getModel().getValueAt(k,8).toString());
                    txtHang.setText(tblDSVeMayBay.getModel().getValueAt(k,6).toString());
				}
        /*boolean a=tblDSVeMayBay.isEditing();
        if(a==false)
        {
            JOptionPane.showMessageDialog(null,"Không được phép điều chỉnh !!!");
        }*/
        tblDSVeMayBay.setDefaultEditor(Object.class, null);
    }//GEN-LAST:event_tblDSVeMayBayMouseClicked
//Kiểm tra giá trị ở TextField Giá Vé
    public static boolean checkNumber(String s)
    {
        for(int i =0 ; i< s.length(); i++){
            if(Character.isDigit(s.charAt(i))){
               
            }else return false;
        }
        return true;
    }
   /* private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
                                String mv = txtMaVe.getText();
                                String gv = txtGiaVe.getText();
                                int flag=0;
                                if("".equals(mv))
                                {
                                    JOptionPane.showMessageDialog(null, "Mã vé trống !");
                                    txtMaVe.requestFocus();
                                }else
                                if("".equals(gv) || checkNumber(txtGiaVe.getText())==false)
                                {
                                    JOptionPane.showMessageDialog(null, "Giá vé không hợp lệ !");
                                    txtGiaVe.setText("0");
                                    txtGiaVe.requestFocus();
                                }
                                for(VeMayBayDTO vmb : VeMayBayBUS.dsvmb)
                                {
                                    if(mv.equals(vmb.getMaVe()))
                                    {
                                        JOptionPane.showMessageDialog(null, "Mã vé bị trùng !");
                                        flag=1;
                                    }
                                }
                                if(flag==0)
                                {            
                                JOptionPane.showMessageDialog(null, "Đã thêm dữ liệu !");
                                VeMayBayDTO vmb=new VeMayBayDTO();
								vmb.setMaVe(txtMaVe.getText());
								vmb.setMaGhe(txtMaGhe.getText());
								vmb.setMaKH(txtMaKH.getText());
								vmb.setMaCB(txtMaCB.getText());
				                                vmb.setTenHangVe(txtTenHangVe.getText());
								vmb.setGiaVe(Integer.valueOf(txtGiaVe.getText()));
								vmb.setHang(txtGiaTriGiam.getText());
                                vmb.setGiaTriGiam(Integer.valueOf(txtGiaTriGiam.getText()));
                                vmb.setVisa(txtVisa.getText());
				
                                Vector row=new Vector();
								row.add(vmb.getMaVe());
								row.add(vmb.getMaGhe());
								row.add(vmb.getMaKH());
								row.add(vmb.getMaCB());
                                row.add(vmb.getTenHangVe());
								row.add(String.valueOf(vmb.getGiaVe()));
								row.add(vmb.getHang());
                                row.add(String.valueOf(vmb.getGiaTriGiam()));
                                row.add(vmb.getVisa());
                                
				model.addRow(row);
				tblDSVeMayBay.setModel(model);
                                VeMayBayBUS bus = new VeMayBayBUS();
				bus.them(vmb);
                                }
    }//GEN-LAST:event_btnThemActionPerformed*/

    private void txtGiaVeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGiaVeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGiaVeActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
                                int i=tblDSVeMayBay.getSelectedRow();
				int k=JOptionPane.showConfirmDialog(null,"Bạn chắc chắn muốn xóa ?");
				if(k==0)
				{
					if(i>=0)
					{
						JOptionPane.showMessageDialog(null,"Đã xóa dữ liệu !");
						VeMayBayBUS bus=new VeMayBayBUS();
						bus.xoa(i, tblDSVeMayBay.getModel().getValueAt(i,0).toString());
						model.removeRow(i);
						tblDSVeMayBay.setModel(model);
						
					}
					else JOptionPane.showMessageDialog(null,"Vui lòng chọn dòng cần xóa !");
				}
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        int k=JOptionPane.showConfirmDialog(null,"Bạn chắc chắn muốn thoát ?");
        if(k==0)
        {
           setVisible(false);
        }
    }//GEN-LAST:event_btnThoatActionPerformed

    private void jrbtnMaVeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbtnMaVeActionPerformed
        txtTimMaVe.setEnabled(true);
        txtTimMaKH.setText("");
        txtTimMaKH.setEnabled(false);
        txtTimMaVe.requestFocus();
    }//GEN-LAST:event_jrbtnMaVeActionPerformed

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        if(jrbtnMaVe.isSelected())
        {
            newTableVMB();
            VeMayBayBUS bus = new VeMayBayBUS();
            bus.timKiem("MaVe",txtTimMaVe.getText());
            newDataModel();
        }
        else if (jrbtnMaKH.isSelected())
        {
            newTableVMB();
            VeMayBayBUS bus = new VeMayBayBUS();
            bus.timKiem("MaKH",txtTimMaKH.getText());
            newDataModel();
        }else
        {
            JOptionPane.showMessageDialog(null,"Vui lòng chọn ô cần tìm !");
        }
       
       
    }//GEN-LAST:event_btnTimActionPerformed
    public void newTableVMB()
	{
		model=new DefaultTableModel();
		Vector header=new Vector();
		header.add("Mã Vé");
		header.add("Mã Ghế");
		header.add("Mã Khách");
		header.add("Mã Chuyến Bay");
		header.add("Tên Hạng Vé");
		header.add("Giá Vé(VND)");
                header.add("Hãng");
                header.add("Giá Trị Giảm(%)");
                header.add("Visa");
		
		if(model.getRowCount()==0)
			model=new DefaultTableModel(header,0);
		tblDSVeMayBay.setModel(model);
	}
	public void newDataModel()
	{
		for(VeMayBayDTO vmb : VeMayBayBUS.dsvmb)
		{
			Vector row=new Vector();
			row.add(vmb.getMaVe());
			row.add(vmb.getMaGhe());
			row.add(vmb.getMaKH());
                        row.add(vmb.getMaCB());
			row.add(vmb.getTenHangVe());
			row.add(vmb.getGiaVe());
			row.add(vmb.getHang());
                        row.add(vmb.getGiaTriGiam());
                        row.add(vmb.getVisa());
			
                        model.addRow(row);
		}
		tblDSVeMayBay.setModel(model);
	}
        public void setTable() 
	{
		VeMayBayBUS bus=new VeMayBayBUS();
		if(VeMayBayBUS.dsvmb==null) bus.docDSVMB();
		
		newTableVMB();
		newDataModel();
	}
        public void xuatFileExcel(JTable table, File file){		
			try{
				FileWriter out = new FileWriter(file);
			// Xuat tieu de bang ra file excel
				for(int i=0; i < table.getColumnCount();i++) {
					out.write(table.getColumnName(i)+"\t");
				}
				out.write("\n");
			// Xuat noi dung bang ra file excel.
				for(int i=0; i < table.getRowCount();i++){
					for(int j=0;j < table.getColumnCount();j++){
							out.write(table.getModel().getValueAt(i,j).toString() + "\t"); // \t de chuyen sang cot moi trong file excel.
						}
					out.write("\n"); // \n de xuong dong moi trong file excel.
				}
				out.close();
			}
			catch(Exception ex) {}

		}
    private void jrbtnMaVeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jrbtnMaVeItemStateChanged
        
    }//GEN-LAST:event_jrbtnMaVeItemStateChanged

    private void btnDatLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatLaiActionPerformed
                                txtMaVe.setText("");
                                txtMaGhe.setText("");
				txtMaKH.setText("");
				txtMaCB.setText("");
				txtTenHangVe.setText("");
				txtGiaVe.setText("0");
                                txtGiaTriGiam.setText("");
                                txtGiaTriGiam.setText("0");
                                txtVisa.setText("");
    }//GEN-LAST:event_btnDatLaiActionPerformed

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
                VeMayBayBUS bus=new VeMayBayBUS();
				bus.docDSVMB();
				model =new DefaultTableModel();
				tblDSVeMayBay.setModel(model);
				setTable();
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void btnXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatActionPerformed
                file =new File("vemaybay.xls");
				xuatFileExcel(tblDSVeMayBay, file);
				JOptionPane.showMessageDialog(null,"Da xuat !");
    }//GEN-LAST:event_btnXuatActionPerformed

    private void txtTimMaVeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimMaVeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimMaVeActionPerformed

    private void jrbtnMaKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbtnMaKHActionPerformed
        txtTimMaKH.setEnabled(true);
        txtTimMaVe.setText("");
        txtTimMaVe.setEnabled(false);
        txtTimMaKH.requestFocus();
    }//GEN-LAST:event_jrbtnMaKHActionPerformed

    private void txtGiaTriGiamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGiaTriGiamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGiaTriGiamActionPerformed

    private void jrbtnTrongNuocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbtnTrongNuocActionPerformed
            newTableVMB();
            VeMayBayBUS bus = new VeMayBayBUS();
            bus.hienThi("MaVe","TN");
            newDataModel();
    }//GEN-LAST:event_jrbtnTrongNuocActionPerformed

    private void jrbtnNgoaiNuocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbtnNgoaiNuocActionPerformed
            newTableVMB();
            VeMayBayBUS bus = new VeMayBayBUS();
            bus.hienThi("MaVe","NN");
            newDataModel();
    }//GEN-LAST:event_jrbtnNgoaiNuocActionPerformed
  
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VeMayBayFRM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VeMayBayFRM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VeMayBayFRM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VeMayBayFRM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VeMayBayFRM().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnDatLai;
    private javax.swing.JButton btnDoc;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnTim;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXuat;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton jrbtnMaKH;
    private javax.swing.JRadioButton jrbtnMaVe;
    private javax.swing.JRadioButton jrbtnNgoaiNuoc;
    private javax.swing.JRadioButton jrbtnTrongNuoc;
    
    private javax.swing.JTextField txtGiaTriGiam;
    private javax.swing.JTextField txtGiaVe;
    private javax.swing.JTextField txtHang;
    private javax.swing.JTextField txtMaCB;
    private javax.swing.JTextField txtMaGhe;
    private javax.swing.JTextField txtMaKH;
    private javax.swing.JTextField txtMaVe;
    private javax.swing.JTextField txtTenHangVe;
    private javax.swing.JTextField txtTimMaKH;
    private javax.swing.JTextField txtTimMaVe;
    private javax.swing.JTextField txtVisa;
    // End of variables declaration//GEN-END:variables
}
